# Generated by Django 6.0.3 on 2026-03-26 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0004_alter_category_image_alter_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="show_icon",
            field=models.BooleanField(
                default=True, help_text="Affiche l’icône dans l’application mobile."
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="show_conditionnement",
            field=models.BooleanField(
                default=True,
                help_text="Autorise le sélecteur de conditionnement côté application.",
            ),
        ),
        migrations.CreateModel(
            name="Conditionnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("piece", "Piece"),
                            ("carton", "Carton"),
                            ("palette", "Palette"),
                        ],
                        default="piece",
                        max_length=24,
                    ),
                ),
                ("unite_par_conditionnement", models.PositiveIntegerField(default=1)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("emplacement", models.CharField(blank=True, max_length=120)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditionnements",
                        to="commerce.product",
                    ),
                ),
            ],
            options={
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.AddField(
            model_name="orderitem",
            name="conditionnement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="commerce.conditionnement",
            ),
        ),
    ]
