# Generated by Django 6.0.3 on 2026-03-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0006_alter_conditionnement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="show_image",
            field=models.BooleanField(
                default=True,
                help_text="Affiche l’image de catégorie dans l’accueil (rayons principaux).",
            ),
        ),
    ]
