# Generated by Django 6.0.3 on 2026-03-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_product_image_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Visuel principal du rayon (bannière / carte d’accueil).', null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL externe optionnelle si aucun fichier n’est téléversé.'),
        ),
    ]
