# Generated by Django 6.0.3 on 2026-03-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0005_conditionnement_category_show_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditionnement",
            name="type",
            field=models.CharField(default="piece", max_length=40),
        ),
    ]
